### PR TITLE
313 Enforce data types for applicant fields

### PR DESCRIPTION
**Pull request by godfreyyeung**
Use changeset validator to regulate format for phone and email fields.
Use HTML Number field to force number entry for zipcode.

Addresses #313. Addresses #298.

### CODE REVIEW

**Comment by hannahkates** [comment]
This also addresses #298.

**Comment by godfreyyeung** [comment]
@hannahkates For phone numbers, do you think it's fine to strictly mandate a 10-digit format?

**Comment by hannahkates** [comment]
@godfreyyeung Hema's comment said that the phone in CRM is a numeric with a max of 10 digits, so we should use that for the validation.

**Comment by godfreyyeung** [comment]
> @godfreyyeung Hema's comment said that the phone in CRM is a numeric with a max of 10 digits, so we should use that for the validation.

oh, perfect!

**Comment by godfreyyeung** [comment]
> Would you mind adding these validations to the `pas-form-validation-messages-display-test`? It's kind of a hefty test but might be nice to have these in there. I don't think applicant validations have been added to that test yet

Sorry saw this after I merged! I'll put it up in a new PR.

**Comment by allthesignals** [comment]
@hannahkates is this still an issue? https://github.com/NYCPlanning/labs-applicant-portal/issues/313

Did this PR not fix it?

**Pull request merged**
