### PR TITLE
Sidebar refactor

### PR DESCRIPTION
**Pull request by andycochran**
This PR… 
- Adds a `<NeedAssistanceMessage />` component (which has DCP contact into that's repeated in all the edit/show form sidebars)
- Adds comments to the edit/show form templates to indicate where the main/sidebar columns start and end
- Renames the `<StickySidebar>` component to `<PageNav>` (for a couple reasons):
  - The `.sticky-sidebar` is only a class on the right grid column that makes it sticky
  - This component itself isn't what needs to be sticky; it doesn't need to be concerned with grid layout
  - The sidebar grid column needs to contain other content that isn't part of form buttons and page navigation (and that content also needs to be sticky)
- Moves the `.sticky-sidebar` class out of the component that handles the form buttons and page navigation

### CODE REVIEW

**Comment by andycochran** [comment]
@allthesignals I've renamed it, but I don' think it belongs under the `packages/` folder, as it's also used for the project template and would be included on other non-package templates as we build them out.

**Comment by allthesignals** [comment]
> @allthesignals I've renamed it, but I don' think it belongs under the `packages/` folder, as it's also used for the project template and would be included on other non-package templates as we build them out.

Okay yeah you're right. Don't you think the /components folder is getting a little messy? Is there another folder it might go under? I need some help keeping the components folder from getting out of control

**Comment by andycochran** [comment]
Maybe `<Ui::Messages::Assistance />`?

**Comment by allthesignals** [comment]
> Maybe `<Ui::Messages::Assistance />`?

But it's pretty domain-specific, right?

**Comment by andycochran** [comment]
Adding a note to #329 ("Reorganize Component Files").

**Pull request merged**
