### PR TITLE
Enforce auth in documents for everything except GET

### PR DESCRIPTION
**Pull request by allthesignals**
This is a temporary fix to allow downloads again. The drawback is that these download links are shareable.

We should revisit this authorization issue when we redo our auth workflow.

The reason this broke was due to my change to authentication: we no longer use cookies to sign API requests. We use authorization headers. However, the download link for documents is a plain HTML link. You can't inject headers in requests for downloads in plain HTML hyperlinks. This meant the request wasn't authenticated.

### CODE REVIEW

**Comment by allthesignals** [comment]
Sorry @trbmcginnis — here's the convo: https://teams.microsoft.com/l/message/19:7d007da085784453b187870f44286da5@thread.skype/1596575663174?tenantId=32f56fc7-5f81-4e22-a95b-15da66513bef&groupId=ce454ad8-a936-456b-8926-c9157c03db79&parentMessageId=1596575663174&teamName=NYC%20Department%20of%20City%20Planning&channelName=Labs%20Engies&createdTime=1596575663174

**Comment by trbmcginnis** [comment]
> Sorry @trbmcginnis — here's the convo: https://teams.microsoft.com/l/message/19:7d007da085784453b187870f44286da5@thread.skype/1596575663174?tenantId=32f56fc7-5f81-4e22-a95b-15da66513bef&groupId=ce454ad8-a936-456b-8926-c9157c03db79&parentMessageId=1596575663174&teamName=NYC%20Department%20of%20City%20Planning&channelName=Labs%20Engies&createdTime=1596575663174

Thanks! Since Teams chats can easily get lost/are more temporary, I'm wondering if after we've had conversations on Teams we can add that info to the issue or to the PR description? It feels like Teams chats are easily missed and if someone revisits this in a couple months they won't know where to find that information

**Comment by allthesignals** [comment]
@trbmcginnis  u bet

**Comment by allthesignals** [comment]
@trbmcginnis  updated PR description. thanks!

**Pull request merged**
