### PR TITLE
Promote develop to qa

### PR DESCRIPTION
**Pull request by bfreeds**
This PR will:
1. Make the delete buttons consistent in the UI.
2. Replace placeholder blocks on the PAS Form View Only page with basic data.

@ksinghprod @bean75 opening this PR so you can merge when you're ready to bring these changes into the QA environment.

### CODE REVIEW

**Comment by andycochran** [comment]
🤔 When these QA PRs sit idle, the change set in the description becomes outdated. Not sure how to handle that.

**Comment by ksinghprod** [comment]
Hi @andycochran @bfreeds should I merge the pull request? Just wanted to verify the Base should be QA, and the compare should be Dev. Please confirm

**Comment by bfreeds** [comment]
@andycochran you're right, that is problematic.  I think we should default then to just not having a description on the PRs that promote to QA (and longer term consider [tagged releases](https://help.github.com/en/github/administering-a-repository/managing-releases-in-a-repository) if we find that this workflow of PRs is confusing or difficult to manage)

**Comment by bfreeds** [comment]
@ksinghprod yep - this can be merged whenever you are ready.  Promoting to QA will have `qa` branch as the base, which will bring develop into qa.  The zenhub board is up-to-date to show the status of the known bugs we're working on (what's _not_ included in this promotion to qa).

**Comment by ksinghprod** [comment]
@bfreeds thanks, done

**Pull request merged**
